### PR TITLE
Update translators to cd24892d3

### PR DESCRIPTION
**Pull request by mvolz**
Update translators to cd24892d3

Change-Id: I705a1af07c2e6eeb7502eea87781a075fd998c02

### CODE REVIEW

**Comment by mvolz** [comment]
I did git bisect to see why this is failing, and it seemed to blame this commit: https://github.com/zotero/translators/commit/56a42bc2485f79ac3f45514a106f6ab4f018dfb4

Which makes sense because that's the only change to TEI.js and the test that's failing is exporting TEI.js :).

**Comment by dstillman** [comment]
@adam3smith: This does, remarkably, appear to be the case. Something about the linting broke the export.

Before:

```
<?xml version="1.0" encoding="UTF-8"?>
<listBibl xmlns="http://www.tei-c.org/ns/1.0"><biblStruct type="newspaperArticle" xml:id="Collins2018" corresp="Q5VYZIG2"><analytic><title level="a">Net Neutrality Has Officially Been Repealed. Here’s How That Could Affect You.</title><author><forename>Keith</forename><surname>Collins</surname></author></analytic><monogr><title level="m">The New York Times</title><idno type="ISSN">0362-4331</idno><imprint><biblScope unit="chapter">Technology</biblScope><date>2018</date><note type="accessed">2018-08-21T08:23:37Z</note><note type="url">https://www.nytimes.com/2018/06/11/technology/net-neutrality-repeal.html</note></imprint></monogr></biblStruct></listBibl>
```

After:

```
<?xml version="1.0" encoding="UTF-8"?>
<listBibl xmlns="http://www.tei-c.org/ns/1.0"/>
```

**Comment by adam3smith** [comment]
@dstillman -- is this serverside only? I just tested export of a newspaper article to TEI in Zoteor 5.0.89 and that works just fine. I'd also be surprised if we hadn't heard at all from the various people using this. Can you replicate this locally?

**Comment by dstillman** [comment]
I didn't try in Zotero, but I can reproduce the failing test with translation-server locally. It was this line:

https://github.com/zotero/translators/commit/56a42bc2485f79ac3f45514a106f6ab4f018dfb4#diff-bb91dd973d3d19e692bb5e6a19530c55R589

Looks like you added the necessary lint exception but changed the assignment by mistake.

**Comment by dstillman** [comment]
TEI now fixed in https://github.com/zotero/translators/commit/ec08a11088542db6f3504aa6c3e651e4d6bdec0e, and I updated the translators here in https://github.com/zotero/translation-server/commit/b0a30f98cf25b66b48e69d816fa41015cfd1009e.

(I think maybe the reason you didn't see this in the client is that the timestamp wasn't updated?)

**Pull request closed without merging**
